name:                crux
version:             0.1.0.0
github:              "epeery/crux"
license:             BSD3
author:              "Eli Peery"
maintainer:          "eli.g.peery@gmail.com"
copyright:           "2019 Eli Peery"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/crux#readme>

dependencies:
- base >= 4.7 && < 5
- text
- aeson
- aeson-pretty
- containers
- time
- bytestring
- directory
- filepath
- path-io
- mtl
- brick
- vty
- vector
- pretty-simple

library:
  source-dirs: src

executables:
  crux:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - crux

tests:
  crux-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - crux
